version: '3.9'

services:
  # node приложение 1; пишет 5 рандомных лога в секунду
  first-app:
    build:
      dockerfile: ./packages/node/first-app.Dockerfile
      context: .
    container_name: first-app
    image: first-app:dev
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: first-app

  # node приложение 2; пишет 5 рандомных лога в секунду
  second-app:
    build:
      dockerfile: ./packages/node/second-app.Dockerfile
      context: .
    container_name: second-app
    image: second-app:dev
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: second-app

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    ports:
      - '24224:24224'
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/etc/fluent-bit/parsers.conf

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: qwerty
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource

volumes:
  grafana-storage:
  clickhouse_data:
